name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    # - run: docker build . --file Dockerfile --tag crypto-historical-data-fetcher:latest
    # - run: docker push crypto-historical-data-fetcher:latest
    # - run: docker logout
